baseURL = "https://juurakkobaking.github.io/"

languageCode = "fi-fi"

title = "Juurakko Baking"

enableGitInfo = true


[params]
    BookRepo = "https://github.com/juurakkobaking/juurakkobaking.github.io"
    BookComments = false
    BookSection = "docs"
    BookSearch = true
    BookLogo = "bread.png"
    BookMenuBundle = "/menu"
